// Written by rotkit carve item-tables: enum UniqueItemId, one member per
// UniqueItems row (carved/data/item_tables/UniqueTables.c) named from its
// TEXT_ID_UNIQUE_* name, plus:
// - the loot_rollBaseItem band boundaries, derived from the UniqueItemFlags
//   ITEM_FLAG_UNIQUE_WEAPON / ITEM_FLAG_CARRIED_PASSIVE runs (weapons, then
//   carried passives, then repeatables);
// - the bands' UniqueGfx.lootType bases (lootType == base + index across
//   both bands, asserted at carve time); each base doubles as the
//   Player.uniqueWeaponsCollected / uniquePassivesCollected bit base.
#pragma once

enum UniqueItemId
{
    UNIQUE_ID_STING = 0,
    UNIQUE_ID_SYMBOLBLADE = 1,
    UNIQUE_ID_GLAMDRING = 2,
    UNIQUE_ID_ORCRIST = 3,
    UNIQUE_ID_NARSIL = 4,
    UNIQUE_ID_HADHAFANG = 5,
    UNIQUE_ID_SILVERAXE = 6,
    UNIQUE_ID_STAFF_OF_FIVE_MAGES = 7,
    UNIQUE_ID_STARFALL_BOW = 8,
    UNIQUE_ID_NIGHTFELL_BOW = 9,
    UNIQUE_ID_CELEBORNS_PHIAL = 10,
    UNIQUE_ID_BOROMIRS_HORN = 11,
    UNIQUE_ID_CYCLOPEDIA_OF_HERBS = 12,
    UNIQUE_ID_SAMS_COOKPOT = 13,
    UNIQUE_ID_FLETCHING_KIT = 14,
    UNIQUE_ID_SCROLLS_OF_MINAS_TIRITH = 15,
    UNIQUE_ID_EVENSTAR_OF_ARWEN = 16,
    UNIQUE_ID_GALADRIELS_PHIAL = 17,
    UNIQUE_ID_FORGOTTEN_PALANTIR = 18,
    UNIQUE_ID_CRACKED_PALANTIR = 19,
    UNIQUE_ID_ORC_DRUM = 20,
    UNIQUE_ID_WOVEN_GOBLIN_DOLL = 21,
    UNIQUE_ID_OLIPHAUNT_IVORY_STATUETTE = 22,
    UNIQUE_ID_ORC_HEAD = 23,
    UNIQUE_ID_SWOLLEN_SPIDER_GLANDS = 24,
    UNIQUE_ID_FEATHERWOOD_FLUTE = 25,
    UNIQUE_ID_KING_ALDAZARS_LONGSWORD = 26,
    UNIQUE_ID_HAWLYS_SWORD_OF_LEAVES = 27,
    UNIQUE_ID_THE_WITCH_KINGS_DAUGHTER = 28,
    UNIQUE_ID_BRAKASHS_DWARF_AXE_OF_HACKING = 29,
    UNIQUE_ID_MEAT_CLEAVER_OF_MAECK = 30,
    UNIQUE_ID_GREEN_MACE_OF_THE_OUTLANDER = 31,
    UNIQUE_ID_CRYSTAL_CROOK_OF_JAS_MYNN = 32,
    UNIQUE_ID_STAFF_OF_BRILEE_THE_SCARLET = 33,
    UNIQUE_ID_OAKSTAFF_OF_OLD_THALCOS = 34,
    UNIQUE_ID_VELLA_OF_LORIENS_GOLDBOW = 35,
    UNIQUE_ID_MAEGBORION_ELFBOW = 36,
    UNIQUE_ID_ORC_LUMPS_BIG_BOW = 37,
    UNIQUE_ID_BLUE_CHAINMAIL_OF_ZEPHYRMASTER = 38,
    UNIQUE_ID_FOMACS_MAIL = 39,
    UNIQUE_ID_SCALEMAIL_OF_MARR_KUZ_THE_TALL = 40,
    UNIQUE_ID_MAGE_CROWN_OF_ULRICK = 41,
    UNIQUE_ID_SHINING_HELM_OF_JAE_SUNBAE = 42,
    UNIQUE_ID_ERLINAS_GUAMANIAN_BOAR_HELM = 43,
    UNIQUE_ID_WIZARD_ROBES_OF_BILROY_THE_BROWN = 44,
    UNIQUE_ID_LOVE_BLESSED_CLOAK_OF_ADIN_ARI = 45,
    UNIQUE_ID_ARAMATS_GARNET_COWL = 46,
    UNIQUE_ID_SINDALVIN_GLOVES_OF_ELF_BOWYERS = 47,
    UNIQUE_ID_DUSTEN_BARDIC_GLOVES = 48,
    UNIQUE_ID_GAUNTLETS_OF_NUMBERS = 49,
    UNIQUE_ID_THE_UNKNOWN_AMULET_OF_KEMPOR = 50,
    UNIQUE_ID_DEVITT_CRYSTAL_AMULET = 51,
    UNIQUE_ID_NICKOHARES_FOOT = 52
};

#define UNIQUE_WEAPON_BAND_END UNIQUE_ID_CELEBORNS_PHIAL
#define UNIQUE_CARRIED_PASSIVE_BAND_END UNIQUE_ID_KING_ALDAZARS_LONGSWORD
#define UNIQUE_ITEM_COUNT (UNIQUE_ID_NICKOHARES_FOOT + 1)

#define LOOT_TYPE_UNIQUE_WEAPON_MIN 0x3d
#define LOOT_TYPE_UNIQUE_PASSIVE_MIN 0x47
