.thumb

hookReplace gfx_fadeInFromBlack, fastFade_fadeInFromBlack
hookReplace gfx_fadeOutToBlack, fastFade_fadeOutToBlack
hookReplace gfx_fadeInFromWhite, fastFade_fadeInFromWhite
hookReplace gfx_fadeOutToWhite, fastFade_fadeOutToWhite
hookReplace gfx_windowFadeInFromBlack, fastFade_windowFadeInFromBlack
hookReplace gfx_windowFadeOutToBlack, fastFade_windowFadeOutToBlack
hookReplace gfx_fadeInFromBlackWhileRunning, fastFade_fadeInFromBlackWhileRunning
hookReplace gfx_fadeOutToBlackWhileRunning, fastFade_fadeOutToBlackWhileRunning
hookReplace gfx_mosaicInFromBlack, fastFade_mosaicInFromBlack
hookReplace gfx_mosaicOutToBlack, fastFade_mosaicOutToBlack
hookReplaceR3 gfx_alphaBlendIn, fastFade_alphaBlendIn
hookReplaceR3 gfx_alphaBlendOut, fastFade_alphaBlendOut
