"""Compiled table-patch entries -> armips .org/.byte splices.

A data-table patch defines only the table ENTRIES it changes, each via
TABLE_ENTRY(type, Table, index) (hacks/tablepatch.h). They compile into a `.tablepatch` section of
one object; this reads each entry symbol's bytes and emits an armips fragment that splices them
over the live table at `<Table> + index*sizeof(entry)`:

    .org CloakPrefixes + 0x0
        .byte 0xf4,0x04,0x03,...   ; CloakPrefixes[0] (12 B)

<Table> resolves via build/game_symbols.inc; the entry symbol's own size is the element
stride. Untouched entries stay base ROM. Run by the Makefile hack recipe.
"""

import os
import re
import subprocess
import sys
import tempfile
from collections import namedtuple

from rotkit.stores import data_symbols

SECTION = ".tablepatch"
SYM_RE = re.compile(r"^__tp_(.+)__(\d+)$")
COUNT_RE = re.compile(r"\[(\d+)\]$")

# One patched entry: its table + index (from the symbol name) and where its bytes sit in SECTION.
Entry = namedtuple("Entry", "table index offset size")


def table_counts() -> dict[str, int]:
    """data-table name -> element count N, from the `<type>[N]` rows of config/data.cfg."""
    counts: dict[str, int] = {}
    for sym in data_symbols():
        match = COUNT_RE.search(sym.type)
        if match:
            counts[sym.name] = int(match.group(1))
    return counts


def read_entries(obj: str) -> list[Entry]:
    """The __tp_ entry symbols in `obj` (offset-in-section + stride), via arm-none-eabi-nm."""
    nm = os.environ.get("NM", "arm-none-eabi-nm")
    res = subprocess.run(
        [nm, "-S", "--defined-only", obj], capture_output=True, text=True, check=True
    )
    entries = []
    for line in res.stdout.splitlines():
        parts = line.split()
        if len(parts) != 4:  # value, size, type, name (unsized syms have 3 -> skip)
            continue
        value, size, _typ, name = parts
        match = SYM_RE.match(name)
        if match:
            entries.append(
                Entry(
                    match.group(1), int(match.group(2)), int(value, 16), int(size, 16)
                )
            )
    return entries


def validate(entries: list[Entry], counts: dict[str, int]) -> None:
    """Exit if an entry names an unknown table, an out-of-range index, or a duplicate (table,index)."""
    seen = set()
    for entry in entries:
        if entry.table not in counts:
            sys.exit(
                f"tablepatch: unknown table '{entry.table}' - add a config/data.cfg row for it first"
            )
        if entry.index >= counts[entry.table]:
            sys.exit(
                f"tablepatch: {entry.table}[{entry.index}] out of range "
                f"(table has {counts[entry.table]} entries)"
            )
        if (entry.table, entry.index) in seen:
            sys.exit(
                f"tablepatch: duplicate entry {entry.table}[{entry.index}] from two enabled patches"
            )
        seen.add((entry.table, entry.index))


def read_section(obj: str) -> bytes:
    """Raw bytes of SECTION in `obj`, via arm-none-eabi-objcopy (empty if the section is absent)."""
    objcopy = os.environ.get("OBJCOPY", "arm-none-eabi-objcopy")
    with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as tmp_file:
        tmp_path = tmp_file.name
    try:
        subprocess.run(
            [objcopy, "-O", "binary", f"--only-section={SECTION}", obj, tmp_path],
            check=True,
        )
        with open(tmp_path, "rb") as fh:
            return fh.read()
    finally:
        os.unlink(tmp_path)


def emit(entries: list[Entry], section: bytes, out: str) -> None:
    """Write the armips fragment: one `.org <Table> + index*stride` / `.byte <entry>` per entry."""
    with open(out, "w") as fh:
        fh.write("; GENERATED by rotkit hack tablepatch - do not edit.\n")
        fh.write(
            "; per-entry data-table splices: .org <Table> + index*stride ; .byte <entry>.\n\n"
        )
        for entry in sorted(entries):
            data = section[entry.offset : entry.offset + entry.size]
            if len(data) != entry.size:
                sys.exit(
                    f"tablepatch: {entry.table}[{entry.index}] truncated in {SECTION} "
                    f"(want {entry.size} B at +0x{entry.offset:x}, got {len(data)})"
                )
            fh.write(f".org {entry.table} + 0x{entry.index * entry.size:x}\n")
            fh.write(
                f"    .byte {','.join(f'0x{byte:02x}' for byte in data)}"
                f"   ; {entry.table}[{entry.index}] ({entry.size} B)\n"
            )


def run(obj: str, out: str) -> None:
    entries = read_entries(obj)
    validate(entries, table_counts())
    section = read_section(obj) if entries else b""
    emit(entries, section, out)
    print(
        f"wrote {os.path.relpath(out)}: {len(entries)} table "
        f"{'entry' if len(entries) == 1 else 'entries'}"
    )
