#include "math.h"
#include "gba.h"
#include "libc.h"
#include "variables.h"

// Octagonal length approximation of a component pair: the longer one plus 3/8 of the shorter.
#define OCTAGONAL_LENGTH(shorter, longer) ((((shorter) * 3) >> 3) + (longer))

/**
 * Seeds the RAM copy of the vector-to-Direction8 lookup table and clears g_Vector2Zero.
 *
 * @romaddress 0x08032754
 */
void math_init(void)
{
    // TODO: This was probably originally initialized with the actual values, with the first memcpy
    // being generated by the compiler. Try removing this when .rodata is better understood.
    Direction8 directions[16];
    memcpy(directions, Direction8sFromVectors, sizeof(directions));

    memcpy(g_Direction8sFromVectors, directions, sizeof(directions));
    g_Vector2Zero.x = 0;
    g_Vector2Zero.y = 0;
}

/**
 * Returns sin(angle) as fp16_16.
 *
 * @romaddress 0x08032788
 */
fp16_16 math_sinFp16(Angle8 angle)
{
    Angle8 index = angle;
    u8 quadrant = index / ANGLE8_QUARTER_TURN;

    if (quadrant & 1)
    {
        // mirror by using wraparound
        index = ANGLE8_HALF_TURN - index;
    }
    if (quadrant & 2)
    {
        // negate; the subtraction offsets quadrant 2 and unwraps quadrant 3
        return -SineQuarterTurn[index - ANGLE8_HALF_TURN];
    }
    return SineQuarterTurn[index];
}

/**
 * Returns cos(angle) as fp16_16.
 *
 * @romaddress 0x080327cc
 */
fp16_16 math_cosFp16(Angle8 angle)
{
    Angle8 index = angle + ANGLE8_QUARTER_TURN;
    u8 quadrant = index / ANGLE8_QUARTER_TURN;

    if (quadrant & 1)
    {
        // mirror by using wraparound
        index = ANGLE8_HALF_TURN - index;
    }

    // negate? the subtraction offsets quadrant 2 and unwraps quadrant 3
    return (quadrant & 2) ? -SineQuarterTurn[index - ANGLE8_HALF_TURN] : SineQuarterTurn[index];
}

/**
 * Returns sin(angle) as fp8_8.
 *
 * @romaddress 0x08032818
 */
fp8_8 math_sinFp8(Angle8 angle)
{
    return math_sinFp16(angle) >> 8;
}

/**
 * Returns cos(angle) as fp8_8.
 *
 * @romaddress 0x0803282c
 */
fp8_8 math_cosFp8(Angle8 angle)
{
    return math_cosFp16(angle) >> 8;
}

/**
 * Returns a * b, truncated toward zero.
 *
 * @romaddress 0x08032840
 */
fp8_8 math_multiplyFp8(fp8_8 a, fp8_8 b)
{
    fp16_16 product = a * b;

    // 8.8 * 8.8 is 16.16. Divide to narrow it back to 8.8.
    product /= FP8_8_ONE;
    return product;
}

/**
 * Returns numerator / denominator, truncated toward zero.
 *
 * @romaddress 0x0803285c
 */
fp8_8 math_divideFp8(fp8_8 numerator, fp8_8 denominator)
{
    return numerator * FP8_8_ONE / denominator;
}

/**
 * Returns 1 / value, truncated toward zero.
 *
 * @romaddress 0x08032874
 */
fp8_8 math_reciprocalFp8(fp8_8 value)
{
    s32 numerator = FP8_8_ONE * FP8_8_ONE;

    return numerator / value;
}

/**
 * Returns a * b. Both operands drop their low 6 bits first, so the product is approximate and
 * overflows once |a * b| reaches 2048.
 *
 * @romaddress 0x0803288c
 */
fp16_16 math_multiplyFp16(fp16_16 a, fp16_16 b)
{
    return ((a >> 6) * (b >> 6)) >> 4;
}

/**
 * Returns 1 / value truncated to a whole number, so any |value| above 1.0 gives 0.
 *
 * @romaddress 0x08032898
 */
fp16_16 math_reciprocalFp16(fp16_16 value)
{
    return (FP16_16_ONE / value) << FP16_16_SHIFT;
}

/**
 * Returns numerator / denominator. The denominator drops its low 6 bits first, so the quotient
 * is approximate and a denominator below 2^-10 divides by zero. The numerator overflows once
 * |numerator| reaches 512.
 *
 * @romaddress 0x080328ac
 */
fp16_16 math_divideFp16(fp16_16 numerator, fp16_16 denominator)
{
    return bios_div(numerator << 6, denominator >> 6) << 4;
}

/**
 * Returns the octagonal length approximation of the given vector.
 *
 * @romaddress 0x080328bc
 */
u32 math_vector2_length(Vector2Int v)
{
    Vector2Int absV = math_vector2_abs(v);
    u32 result;

    if (absV.x <= absV.y)
    {
        result = OCTAGONAL_LENGTH(absV.x, absV.y);
    }
    else
    {
        result = OCTAGONAL_LENGTH(absV.y, absV.x);
    }
    return result;
}

/**
 * Componentwise addition: out = a + b.
 *
 * @romaddress 0x080328f0
 */
void math_vector2_add(const Vector2Fp16 *a, const Vector2Fp16 *b, Vector2Fp16 *out)
{
    out->x = a->x + b->x;
    out->y = a->y + b->y;
}

/**
 * Componentwise subtraction: out = a - b.
 *
 * @romaddress 0x08032908
 */
void math_vector2_subtract(const Vector2Fp16 *a, const Vector2Fp16 *b, Vector2Fp16 *out)
{
    out->x = a->x - b->x;
    out->y = a->y - b->y;
}

/**
 * Componentwise copy: dst = src.
 *
 * @romaddress 0x08032920
 */
void math_vector2_copy(const Vector2Fp16 *src, Vector2Fp16 *dst)
{
    dst->x = src->x;
    dst->y = src->y;
}

/**
 * fp16_16 -> integer conversion, componentwise (>> 16, so negatives floor). The result is
 * narrowed to s16: integer parts outside -32768..32767 wrap.
 *
 * @param src the fp16_16 coordinates (e.g. &Actor.coords)
 * @param dst receives the integer coordinates
 *
 * @romaddress 0x0803292c
 */
void math_vector2_fromFp16(const Vector2Fp16 *src, Vector2Int *dst)
{
    dst->x = (s16)(src->x >> 16);
    dst->y = (s16)(src->y >> 16);
}

/**
 * Integer -> fp16_16 conversion, componentwise (<< 16).
 *
 * @romaddress 0x0803293c
 */
void math_vector2_toFp16(const Vector2Int *src, Vector2Fp16 *dst)
{
    dst->x = src->x << 16;
    dst->y = src->y << 16;
}

/**
 * Componentwise equality.
 *
 * @romaddress 0x0803294c
 */
bool math_vector2_equals(const Vector2Fp16 *a, const Vector2Fp16 *b)
{
    bool equal = FALSE;

    if (a->x == b->x && a->y == b->y)
    {
        equal = TRUE;
    }
    return equal;
}

/**
 * Classify a vector into a Direction8 (e.g. attacker->victim for knockback/impact
 * facing). Uses sign and dominant axis of (v.x, v.y); +y is south. Scale-invariant:
 * callers pass both fp16_16 and integer vectors.
 *
 * @romaddress 0x08032970
 */
Direction8 math_vector2_direction8(Vector2Int v)
{
    u8 flags = 0;

    if (v.x < 0)
    {
        v.x = -v.x;
        flags |= 1;
    }
    if (v.y < 0)
    {
        v.y = -v.y;
        flags |= 2;
    }
    if (v.x > v.y * 2)
    {
        flags |= 4;
    }
    if (v.x * 2 < v.y)
    {
        flags |= 8;
    }
    return g_Direction8sFromVectors[flags];
}

/**
 * Classify an fp16_16 vector into a 32-way direction index via BIOS ArcTan2.
 *
 * @romaddress 0x080329b4
 */
Direction32 math_vector2_direction32(Vector2Fp16 v)
{
    s16 x16;
    s16 y16;
    s32 angle;
    u32 angle16;
    u32 sector;

    v.x >>= 16;
    v.y >>= 16;
    x16 = v.x;
    y16 = v.y;
    angle = bios_arcTan2(x16, y16);

    angle16 = (u16)angle;
    // 32 sectors over the 0..0xffff angle; the +0x800 pulls each sector boundary down by 64
    // angle units, a 32nd of a sector. ArcTan2's origin is east, so adding DIRECTION32_EAST
    // puts sector 0 on north.
    sector = (angle16 * DIRECTION32_COUNT + 0x800) >> 16;
    sector += DIRECTION32_EAST;
    return sector & (DIRECTION32_COUNT - 1);
}

/**
 * Octagonal distance approximation (max + 3/8*min) between two positions. Scale-invariant:
 * the result is in the same unit as the inputs (callers use both integer and fp16_16).
 *
 * @romaddress 0x080329e0
 */
u32 math_vector2_distance(Vector2Int a, Vector2Int b)
{
    Vector2Int absDiff = math_vector2_abs(math_vector2_diff(a, b));

    if (absDiff.x <= absDiff.y)
    {
        return OCTAGONAL_LENGTH(absDiff.x, absDiff.y);
    }
    return OCTAGONAL_LENGTH(absDiff.y, absDiff.x);
}

/**
 * Rotate a 32-way direction one sector toward target, taking the shorter way around the circle.
 *
 * @param outStep receives the step that was taken (+1 or -1)
 *
 * @romaddress 0x08032a1c
 */
Direction32 math_vector2_stepDirection32(Direction32 current, Direction32 target, s8 *outStep)
{
    if (((current - target) & (DIRECTION32_COUNT - 1)) <= DIRECTION32_COUNT / 2)
    {
        *outStep = -1;
    }
    else
    {
        *outStep = 1;
    }
    current += *outStep;
    // the step wrapped the u8: DIRECTION32_COUNT stepped up past the last sector, anything
    // else stepped down below the first
    if (current < DIRECTION32_COUNT)
    {
        return current;
    }
    if (current == DIRECTION32_COUNT)
    {
        return DIRECTION32_NORTH;
    }
    return DIRECTION32_COUNT - 1;
}

/**
 * Returns base * percent / 100, truncated toward zero.
 *
 * @romaddress 0x08032a5c
 */
s32 math_percentOf(s32 base, u16 percent)
{
    return bios_div(base * percent, 100);
}

/**
 * Returns value * 100 / total, truncated toward zero. The inverse of math_percentOf.
 *
 * @romaddress 0x08032a70
 */
s32 math_percentage(s32 value, s32 total)
{
    return bios_div(value * 100, total);
}

/**
 * Returns the given sign-magnitude value as fp16_16: bit 15 is the sign, the low 15 bits
 * are the magnitude in 7.8 format.
 *
 * @romaddress 0x08032a80
 */
fp16_16 math_signMagnitudeToFp16(s16 value)
{
    s32 scaled = (value << 8) & 0x7fffff;

    if (value < 0)
    {
        scaled = -scaled;
    }
    return scaled;
}

/**
 * Returns numerator / denominator as fp16_16, truncated toward zero. Overflows once
 * |numerator| reaches 32768.
 *
 * @romaddress 0x08032a9c
 */
fp16_16 math_divideIntToFp16(s32 numerator, s32 denominator)
{
    return (numerator << 16) / denominator;
}
