#include "libc.h"
#include "variables.h"
#include "vector2.h"

/**
 * Seeds the RAM copy of the vector-to-Direction8 lookup table and clears g_Vector2Zero.
 *
 * @romaddress 0x08032754
 */
void vector2_init(void)
{
    // TODO: This was probably originally initialized with the actual values, with the first memcpy
    // being generated by the compiler. Try removing this when .rodata is better understood.
    Direction8 directions[16];
    memcpy(directions, Direction8sFromVectors, sizeof(directions));

    memcpy(g_Direction8sFromVectors, directions, sizeof(directions));
    g_Vector2Zero.x = 0;
    g_Vector2Zero.y = 0;
}
